import request from "@/utils/request";

export function saveLineEdit(data) {
  return request({
    url: "/order/lineUpkeep",
    method: "post",
    data
  })
}

export function getLineDetail(data) {
  return request({
    url: "/order/lineInfo",
    method: "post",
    data
  })
}
export const Config = [
  { FIELD: "", LABEL: "收发货信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, ISDISABLED: 1 },
  // { FIELD: "", LABEL: "发货方信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, ISDISABLED: 1 },
  { FIELD: "SENDCOMPANY", LABEL: "发货方", COL: 6, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0 },
  { FIELD: "PK_SENDADDRESS", LABEL: "围栏", COL: 6, CONTROLS: "ExSelectSearch", MAXLENGTH: "200", ISSHOW: 1, OTHER: "/oms/component/getSelectTypeList?TYPE=311&FENCETYPE=circle?PK_CUSTOMER=PK_SENDCOMPANY?SENDADDRESSNAME=LABEL&STARTLNGLAT=LONANDLAT&SENDCONTPSON=CONTACTS&SENDCONTTEL=CONTACTTEL", ISREQUIRE: 1, REVERFIELD: "SENDADDRESSNAME" },
  { FIELD: "SENDADDRESSNAME", LABEL: "围栏名称", COL: 6, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 0, ISREQUIRE: 0 },
  { FIELD: "SENDCONTPSON", LABEL: "发货联系人", COL: 6, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, },
  { FIELD: "SENDCONTTEL", LABEL: "联系人电话", COL: 6, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, REULS: "Mobile", },
  // { FIELD: "", LABEL: "收货方信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, ISDISABLED: 1 },
  { FIELD: "RECVCOMPANY", LABEL: "收货方", COL: 6, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0 },
  { FIELD: "PK_RECVADDRESS", LABEL: "围栏", COL: 6, CONTROLS: "ExSelectSearch", MAXLENGTH: "200", ISSHOW: 1, OTHER: "/oms/component/getSelectTypeList?TYPE=311&FENCETYPE=circle?PK_CUSTOMER=PK_RECECOMPANY?RECVADDRESSNAME=LABEL&ENDLNGLAT=LONANDLAT&RECVCONTPSON=CONTACTS&RECVCONTTEL=CONTACTTEL", ISREQUIRE: 1, REVERFIELD: "RECVADDRESSNAME" },
  { FIELD: "RECVADDRESSNAME", LABEL: "围栏名称", COL: 6, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 0, ISREQUIRE: 0 },
  { FIELD: "RECVCONTPSON", LABEL: "收货联系人", COL: 6, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, },
  { FIELD: "RECVCONTTEL", LABEL: "联系人电话", COL: 6, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, REULS: "Mobile", },
  { FIELD: "ISSUB", LABEL: "监管", COL: 6, CONTROLS: "ExSwitch", DEFAULTVAL: "0", MAXLENGTH: 1, ISSHOW: 1, ISREQUIRE: 0, },
  { FIELD: "", LABEL: "路线信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, ISREQUIRE: 0, ISDISABLED: 1 },
  { FIELD: "DISTANCE", LABEL: "预计距离", COL: 6, CONTROLS: "slot", MAXLENGTH: "", ISSHOW: 1, ISREQUIRE: 1, ISDISABLED: 1, SUFFIX: "米" },
  { FIELD: "DURATION", LABEL: "预计时长", COL: 6, CONTROLS: "slot", MAXLENGTH: "", ISSHOW: 1, ISREQUIRE: 1, ISDISABLED: 1, SUFFIX: "秒" },
]