import request from '@/utils/request'

// 获取订单子表
export function getOrderInfo(data) {
  return request({
    url: "/oms/ddRepCarXc/orderDtl",
    method: "post",
    data
  })
}

// 保存
export function savePz(data) {
  return request({
    url: "/oms/od-order-verb/transport",
    method: "post",
    data
  })
}

// 检查车价
export function checkChejia(data) {
  return request({
    url: "/oms/odLimitPrice/check",
    method: "post",
    data
  })
}

export const formConfig = [
  { FIELD: "", LABEL: "基本信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "PK_CARNO", LABEL: "车辆", COL: 8, CONTROLS: "ExSelectSearch", MAXLENGTH: "200", ISSHOW: 0, OTHER: "/oms/ddRepCarXc/listInfo???PK_INVOIC=PK_INVOIC&INVOIC_COMPANY=INVOIC_COMPANY&BALATYPE=BALATYPE&CARNO=LABEL&PKOWNER=PKOWNER&OWNERSHIP=OWNERSHIP&OWNERSHIPTEL=OWNERSHIPTEL&CARNOG=CARNOG&CARRIER=CARRIER&PK_CARRIER=PK_CARRIER&YOILCARD=YOILCARD&NOILCARD=NOILCARD&BANKACCOUNT=BANKACCOUNT&BANK=BANK&INSURECOST=INSURECOST&CONTRACTTYPE=CONTRACTTYPE&CONTRACTNO=CONTRACTNO&CONTRACTEXPIRETIME=CONTRACTEXPIRETIME&CONTRACTENTERTIME=CONTRACTENTERTIME&CONTRACTURL=CONTRACTURL&CONTRACTVEMO=CONTRACTVEMO&hashtinfo=CONTRACTNO", ISREQUIRE: 1, },
  { FIELD: "CARNO", LABEL: "车辆", COL: 8, CONTROLS: "ExSelectModal", MAXLENGTH: "200", ISSHOW: 1, REVERFIELD: "CARNO", OTHER: "/oms/ddRepCarXc/listInfo??!BILLNO=BILLNO?CARNO=LABEL&PK_CARNO=VALUE&PK_INVOIC=PK_INVOIC&INVOIC_COMPANY=INVOIC_COMPANY&BALATYPE=BALATYPE&PKOWNER=PKOWNER&OWNERSHIP=OWNERSHIP&OWNERSHIPTEL=OWNERSHIPTEL&CARNOG=CARNOG&CARRIER=CARRIER&PK_CARRIER=PK_CARRIER&YOILCARD=YOILCARD&NOILCARD=NOILCARD&BANKACCOUNT=BANKACCOUNT&BANK=BANK&INSURECOST=INSURECOST&CONTRACTTYPE=CONTRACTTYPE&CONTRACTNO=CONTRACTNO&CONTRACTEXPIRETIME=CONTRACTEXPIRETIME&CONTRACTENTERTIME=CONTRACTENTERTIME&CONTRACTURL=CONTRACTURL&CONTRACTVEMO=CONTRACTVEMO&hashtinfo=CONTRACTNO&&OPENINGBANK=BANK&CONTACTTEL=CONTACTTEL&BANKDTLNAME=BANKDTLNAME&DRIVERNAME=DRIVER_NAME1&PK_DRIVER=PK_DRIVER1&DRIVERPHONE=DRIVER_PHONE1&DRIVERIDCARD=", ISREQUIRE: 1, SLOTCFG: "MU231213621038,PG231213300185,80%*50%" },
  { FIELD: "PK_DRIVER", LABEL: "司机", COL: 8, CONTROLS: "ExSelectModal", MAXLENGTH: "200", ISSHOW: 0, REVERFIELD: "DRIVERNAME", },
  { FIELD: "DRIVERNAME", LABEL: "司机", COL: 8, CONTROLS: "ExSelectModal", MAXLENGTH: "200", ISSHOW: 1, REVERFIELD: "DRIVERNAME", OTHER: "/base/driver/getPageList??PK_OWNER=PKOWNER?PK_DRIVER=PK_USER&DRIVERNAME=VNAME&DRIVERPHONE=DRTEL&DRIVERIDCARD=DRID", ISREQUIRE: 1, SLOTCFG: "MU221025281210,PG221025175291,80%*50%" },
  { FIELD: "DRIVERPHONE", LABEL: "司机电话", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 1, },
  { FIELD: "PKOWNER", LABEL: "承运商", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 0, OTHER: "", ISREQUIRE: 1, },
  { FIELD: "OWNERSHIP", LABEL: "承运商", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "OWNERSHIPTEL", LABEL: "电话", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "CARNOG", LABEL: "挂车号", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "BALATYPE", LABEL: "结算方式", COL: 8, CONTROLS: "ExSelect", MAXLENGTH: "200", ISSHOW: 1, OTHER: "${BALATYPE}", ISREQUIRE: 1, },
  // { FIELD: "TOTAL", LABEL: "子表总运费", COL: 8, CONTROLS: "ExNumber", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"CALC":"TOTAL-OILFREE-INSURECOST=HSTOTAL"}' },
  { FIELD: "FREIGHT", LABEL: "总运费", COL: 8, CONTROLS: "ExNumber", MAXLENGTH: "", ISSHOW: 1, OTHER: "", ISREQUIRE: 1, },
  { FIELD: "SUBLIST", LABEL: "子表", COL: 24, CONTROLS: "subTable", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "OILTYPE", LABEL: "油卡类型", COL: 8, CONTROLS: "ExSelect", MAXLENGTH: "200", ISSHOW: 1, OTHER: "${OILTYPE}", ISREQUIRE: 0, },
  { FIELD: "OILFREE", LABEL: "油费", COL: 8, CONTROLS: "ExNumber", MAXLENGTH: "", ISSHOW: 1, OTHER: "", ISREQUIRE: 1, },
  { FIELD: "NOILCARD", LABEL: "内部卡号", COL: 8, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 2, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISSHOW":"Data.OILTYPE == 1","ISREQUIRE":"Data.OILTYPE == 1"}' },
  { FIELD: "YOILCARD", LABEL: "外部卡号", COL: 8, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 2, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISSHOW":"Data.OILTYPE == 2","ISREQUIRE":"Data.OILTYPE == 2"}' },
  { FIELD: "CARRIER", LABEL: "运费结算客户", COL: 8, CONTROLS: "ExSelectModal", MAXLENGTH: "200", ISSHOW: 1, OTHER: "/base/bdcarrier/listInfo???CARRIER=VNAME&BANKACCOUNT=BANKACCOUNT&BANK=BANK&OPENINGBANK=OPENINGBANK&CONTACTTEL=CONTACTTEL&BANKDTLNAME=BANKDTLNAME", SLOTCFG: "MU221026213957,PG221026206132", ISREQUIRE: 1, REVERFIELD: "CARRIER" },
  { FIELD: "PK_CARRIER", LABEL: "运费结算客户", COL: 8, CONTROLS: "ExTextBox", MAXLENGTH: "200", ISSHOW: 0, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "BANK", LABEL: "开户行", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "BANKACCOUNT", LABEL: "运费结算卡号", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  // { FIELD: "INSURECOST", LABEL: "保险费用", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "REALITYINSURECOST", LABEL: "实际保险费用", COL: 8, CONTROLS: "ExSelect", MAXLENGTH: "", DEFAULTVAL: "60", ISSHOW: 1, OTHER: '${BXFY}', ISREQUIRE: 1, },
  { FIELD: "LSZDPSNID", LABEL: "配载人员", COL: 8, CONTROLS: "ExSelectSearch", DEFAULTVAL: "U$USERID", MAXLENGTH: "200", ISSHOW: 1, OTHER: "/sys/userType/getUserByDept?PK_DEPT=DEP230921000001??LSZDPSN=LABEL", ISREQUIRE: 1, REVERFIELD: "LSZDPSN" },
  { FIELD: "LSZDPSN", LABEL: "配载人员", COL: 8, CONTROLS: "read", DEFAULTVAL: "U$VNAME", MAXLENGTH: "200", ISSHOW: 0, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "PK_INVOIC", LABEL: "所属公司", COL: 8, CONTROLS: "ExSelectGroup", DEFAULTVAL: "auto", MAXLENGTH: "200", ISSHOW: 1, OTHER: "/sys/baInvoicingCompany/listInfo???INVOIC_COMPANY=LABEL", REVERFIELD: "INVOIC_COMPANY", ISREQUIRE: 1, },
  { FIELD: "INVOIC_COMPANY", LABEL: "所属公司", COL: 8, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 0, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "ORDERQUALITY", LABEL: "订单质量", COL: 8, CONTROLS: "ExSelect", MAXLENGTH: "200", ISSHOW: 1, OTHER: "${ORDERQUALITY}", ISREQUIRE: 1, },
  { FIELD: "ISOPEN", LABEL: "网货", COL: 8, CONTROLS: "ExSwitch", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"CLEAR":"OPENSYSTEM"}' },
  { FIELD: "", LABEL: "网货信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 2, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISSHOW":"Data.ISOPEN==1"}' },
  { FIELD: "OPENSYSTEM", LABEL: "网货平台", COL: 8, CONTROLS: "ExSelect", MAXLENGTH: "200", ISSHOW: 2, OTHER: "${OPENSYSTEM}", ISREQUIRE: 1, LINKAGE: '{"ISSHOW":"Data.ISOPEN==1","ISREQUIRE":"Data.ISOPEN==1"}' },
  { FIELD: "OPENINGBANK", LABEL: "开户行", COL: 8, CONTROLS: "ExReadCard", MAXLENGTH: "", ISSHOW: 2, OTHER: "", ISREQUIRE: 1, LINKAGE: '{"ISSHOW":"Data.ISOPEN==1","ISREQUIRE":"Data.ISOPEN==1"}' },
  { FIELD: "BANKDTLNAME", LABEL: "开户行省市区", COL: 8, CONTROLS: "ExReadCard", MAXLENGTH: "", ISSHOW: 2, OTHER: "", ISREQUIRE: 1, LINKAGE: '{"ISSHOW":"Data.ISOPEN==1","ISREQUIRE":"Data.ISOPEN==1"}' },
  { FIELD: "CONTACTTEL", LABEL: "开户人电话", COL: 8, CONTROLS: "ExReadCard", MAXLENGTH: "", ISSHOW: 2, OTHER: "", ISREQUIRE: 1, LINKAGE: '{"ISSHOW":"Data.ISOPEN==1","ISREQUIRE":"Data.ISOPEN==1"}' },
  { FIELD: "", LABEL: "保险信息", COL: 24, CONTROLS: "ExTabs", DEFAULTVAL: "open", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "ISBX", LABEL: "购买保险", COL: 8, CONTROLS: "ExRadio", DEFAULTVAL: "1", MAXLENGTH: "200", ISSHOW: 1, OTHER: JSON.stringify([{ LABEL: '是', VALUE: '1' }, { LABEL: '否', VALUE: '0' }]), ISREQUIRE: 1, LINKAGE: '{"CLEAR":"BXNO"}' },
  { FIELD: "POLICYNO", LABEL: "保险单号", COL: 8, CONTROLS: "ExTextBox", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 2, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISSHOW":"Data.ISBX==1","ISREQUIRE":"Data.ISBX==1"}' },
  { FIELD: "TASKTYPE", LABEL: "配载类型", ISSHOW: 0, DEFAULTVAL: "2" }
]
export const tableConfig = [{
  _rowConfig: { FIELD: "SUBLIST", LABEL: "子表", COL: 24, CONTROLS: "subTable", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  FIELD: "SUBLIST",
  BUTTON: [{ ACTION: "EDIT" }],
  COLUMNS: [
    { FIELD: "ORDERCODE", LABEL: "发货单号", COL: 8, WIDTH: 180, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 1, ISEDIT: 0, OTHER: "", ISREQUIRE: 0, },
    { FIELD: "PKDESTINATION", LABEL: "目的地", COL: 8, WIDTH: 160, CONTROLS: "ExSelectSearch", MAXLENGTH: "200", ISSHOW: 1, ISEDIT: 1, OTHER: "/base/bdDestination/listInfo???DESTINATION=LABEL", REVERFIELD: "DESTINATION", ISREQUIRE: 1, },
    { FIELD: "DESTINATION", LABEL: "目的地", COL: 8, WIDTH: 160, CONTROLS: "read", MAXLENGTH: "200", ISSHOW: 0, ISEDIT: 0, OTHER: "", ISREQUIRE: 1, },
    { FIELD: "NNUM", LABEL: "重量", COL: 8, WIDTH: 120, CONTROLS: "read", SUFFIX: "吨", MAXLENGTH: "", ALIGN: "right", ISSHOW: 1, OTHER: "", ISEDIT: 0, ISREQUIRE: 0, },
    { FIELD: "RIGTAXPRICE", LABEL: "含税单价", COL: 8, WIDTH: 120, CONTROLS: "ExNumber", SUFFIX: "元/吨", ALIGN: "right", MAXLENGTH: "", ISSHOW: 1, OTHER: "", ISEDIT: 1, ISREQUIRE: 1, LINKAGE: '{"CALC":"Data.NNUM*Data.RIGTAXPRICE=RIGTAXMGY","SUM":"RIGTAXMGY=M$TOTAL"}' },
    { FIELD: "RIGTAXMGY", LABEL: "含税金额", COL: 8, WIDTH: 100, CONTROLS: "read", SUFFIX: "元", MAXLENGTH: "", ALIGN: "right", ISSHOW: 1, OTHER: "", ISEDIT: 0, ISREQUIRE: 0, },
    { FIELD: "RECVADDRESS", LABEL: "收货地址", COL: 24, WIDTH: 500, CONTROLS: "ExTextarea", MAXLENGTH: "200", ISSHOW: 1, ISEDIT: 0, OTHER: "", ISREQUIRE: 0, },
  ],
}]

export const htConfig = [
  { FIELD: "hashtinfo", LABEL: "是否存在合同信息", COL: 8, CONTROLS: "read", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 0, OTHER: "", ISREQUIRE: 0, LINKAGE: '' },
  { FIELD: "CONTRACTTYPE", LABEL: "合同类型", COL: 8, CONTROLS: "ExSelect", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 1, OTHER: "${CONTRACTTYPE}", ISREQUIRE: 1, },
  { FIELD: "CONTRACTNO", LABEL: "合同号", COL: 8, CONTROLS: "ExTextBox", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISREQUIRE":"Data.CONTRACTTYPE==1"}' },
  { FIELD: "CONTRACTEXPIRETIME", LABEL: "合同开始时间", COL: 8, CONTROLS: "ExDate", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, LINKAGE: '{"ISREQUIRE":"Data.CONTRACTTYPE==1"}' },
  { FIELD: "CONTRACTENTERTIME", LABEL: "合同结束时间", COL: 8, CONTROLS: "ExDate", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
  { FIELD: "CONTRACTURL", LABEL: "合同图片", COL: 8, CONTROLS: "ExPhoto", DEFAULTVAL: "", MAXLENGTH: "", ISSHOW: 1, OTHER: "", ISREQUIRE: 1, LINKAGE: '{"ISREQUIRE":"Data.CONTRACTTYPE==1"}' },
  { FIELD: "CONTRACTVEMO", LABEL: "合同备注", COL: 8, CONTROLS: "ExTextBox", DEFAULTVAL: "", MAXLENGTH: "200", ISSHOW: 1, OTHER: "", ISREQUIRE: 0, },
]